@startuml
class ホテル {
    -部屋リスト : List<部屋>
    -利用者リスト : List<利用者>
    +予約(利用者, 部屋) : 予約
}

class 部屋 {
    -部屋番号 : 文字列
}

class 利用者 {
    -名前 : 文字列
}

class 予約 {
    -利用者 : 利用者
    -部屋 : 部屋
    -開始日 : 日付
    -終了日 : 日付
}

ホテル o-- 部屋 : 部屋リスト
ホテル o-- 利用者 : 利用者リスト
ホテル *-- 予約 : 予約
@enduml
