@startuml

class ドリンク {
    +サイズ
    +種類
    +値段
}

class フード {
    +名前
    +値段
}

class 商品 {
    +名前
    +値段
}

class 注文明細 {
    +商品リスト
    +数量
    +小計
}

class 注文 {
    +注文明細リスト
    +合計金額
    +割引クーポン適用()
    +お会計()
}

class カップ {
    +サイズ
}

class 材料 {
    +名前
}

class ハンバーガー {
    +材料リスト
}

class 割引クーポン {
    +割引率
    +適用条件
}

class レシピ {
    +材料リスト
    +手順リスト
}

class ポテト {
    +サイズ
}

ドリンク <-- 商品
フード <-- 商品
商品 "1" o-- "1" 注文明細
注文明細 "1" o-- "1" 注文
ドリンク "1" o-- "1" カップ
ハンバーガー "1" o-- "1..*" 材料
ポテト "1" o-- "1" カップ
商品 "1" o-- "1..*" レシピ
ハンバーガー "1" o-- "1" レシピ
注文明細 "1" o-- "1" レシピ
商品 "1" o-- "1..*" 割引クーポン
ハンバーガー "1" o-- "1..*" 注文明細
ポテト "1" o-- "1..*" 注文明細

@enduml
