@startuml
[*] -right-> メニュー

メニュー -right-> [*]   
メニュー ---> 予約と確認   
予約と確認 ---> メニュー     
メニュー ---> あなたの順番   
予約と確認 -right-> あなたの順番     
あなたの順番 -right-> 予約と確認     
メニュー ---> 今の順番  
今の順番 ---> メニュー   
@enduml